[global]
width = 350
height = 100
offset = 12x12
origin = top-right
transparency = 10
frame_color = "@{outline.dark.hex}"
frame_width = 1
corner_radius = 12
font = Inter 11
padding = 12
horizontal_padding = 16
icon_theme = WhiteSur-dark
max_icon_size = 48
background = "@{surface_container.dark.hex}"
foreground = "@{on_surface.dark.hex}"

[urgency_low]
background = "@{surface_container.dark.hex}"
foreground = "@{on_surface_variant.dark.hex}"
timeout = 5

[urgency_normal]
background = "@{surface_container.dark.hex}"
foreground = "@{on_surface.dark.hex}"
timeout = 8

[urgency_critical]
background = "@{error_container.dark.hex}"
foreground = "@{on_error_container.dark.hex}"
timeout = 0
