[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = "Swww"
prefix = "@"
swww_options = [
    "--transition-type", "center",
    "--transition-duration", "1",
]

[config.reload_apps_list]
waybar = true
kitty = true
dunst = true
gtk_theme = false

[templates.waybar-colors]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.kitty-colors]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.dunst-colors]
input_path = "~/.config/matugen/templates/dunst-colors.conf"
output_path = "~/.config/dunst/colors.conf"
post_hook = "dunstctl reload"

[templates.fuzzel-colors]
input_path = "~/.config/matugen/templates/fuzzel-colors.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.niri-colors]
input_path = "~/.config/matugen/templates/niri-colors.kdl"
output_path = "~/.config/niri/colors.kdl"
post_hook = "niri msg action load-config-file"
