[global]
frame_color = "@{outline.dark.hex}"

[urgency_low]
background = "@{surface_container.dark.hex}"
foreground = "@{on_surface_variant.dark.hex}"

[urgency_normal]
background = "@{surface_container.dark.hex}"
foreground = "@{on_surface.dark.hex}"

[urgency_critical]
background = "@{error_container.dark.hex}"
foreground = "@{on_error_container.dark.hex}"
