$active_border = rgba(@{primary.dark.strip}ee)
$inactive_border = rgba(@{outline_variant.dark.strip}aa)
$shadow_color = rgba(@{shadow.dark.strip}88)

general {
    col.active_border = $active_border
    col.inactive_border = $inactive_border
}

decoration {
    shadow {
        color = $shadow_color
    }
}
