$primary = rgba(@{primary.dark.strip}ee)
$on_primary = rgba(@{on_primary.dark.strip}ff)
$surface = rgba(@{surface.dark.strip}ff)
$surface_variant = rgba(@{on_surface_variant.dark.strip}aa)
$outline = rgba(@{outline.dark.strip}aa)
$shadow = rgba(@{shadow.dark.strip}88)

general {
    col.active_border = $primary
    col.inactive_border = $surface_variant
}

decoration {
    shadow {
        color = $shadow
    }
}
